### ISSUE TITLE
Jetbrains Mono causes Unreadable code 

### ISSUE THREAD

**Issue by Souravgoswami** [ruby-news/ruby-news.github.io#40]
The font jetbrains mono makes the code unreadable by concatenating characters like !=.

For example:

![image](https://user-images.githubusercontent.com/37468605/130745922-793e40d7-3add-4c34-a3e2-dc1fc2d5074d.png)

**Comment by Souravgoswami** [comment]
Hi @Sergyenko, I didn't detect this before, should I change the font to roboto-mono?

![image](https://user-images.githubusercontent.com/37468605/130746068-5cae0820-e766-42e8-ab43-375fddf1aee8.png)

**Comment by Sergyenko** [comment]
LGTM
